kind: pipeline
type: docker
name: func-test

steps:
- name: run-test
  image: vivado:2019.2
  commands:
  - export SIMULATION=sim_1
  - /opt/Xilinx/Vivado/2019.2/bin/vivado -mode tcl -source scripts/run_simulation.tcl loooongson/soc_axi_func/run_vivado/mycpu_prj1/mycpu.xpr
  - grep '\-\-\-\-PASS!!!' loooongson/soc_axi_func/run_vivado/mycpu_prj1/mycpu.sim/sim_1/behav/xsim/simulate.log

